[package]
name = "test-node"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"
publish = false

[dependencies]
futures = "0.3.5"
log = "0.4.11"
structopt = "0.3.16"
test-runtime = { path = "../runtime" }

sc-basic-authorship = "0.8.0-rc5"
sc-cli = "0.8.0-rc5"
sc-client-api = "2.0.0-rc5"
sc-consensus = "0.8.0-rc5"
sc-consensus-aura = "0.8.0-rc5"
sc-executor = "0.8.0-rc5"
sc-finality-grandpa = "0.8.0-rc5"
sc-network = "0.8.0-rc5"
sc-service = "0.8.0-rc5"
sc-transaction-pool = "2.0.0-rc5"
sp-consensus = "0.8.0-rc5"
sp-consensus-aura = "0.8.0-rc5"
sp-core = "2.0.0-rc5"
sp-finality-grandpa = "2.0.0-rc5"
sp-inherents = "2.0.0-rc5"
sp-runtime = "2.0.0-rc5"
sp-transaction-pool = "2.0.0-rc5"
sunshine-client-utils = { git = "https://github.com/sunshine-protocol/sunshine-core" }

[build-dependencies]
substrate-build-script-utils = "2.0.0-rc5"
