[package]
name = "test-node"
version = "0.1.0"
authors = ["4meta5"]
edition = "2018"
publish = false

[dependencies]
sc-executor = "0.8.0-rc5"
sp-core = "2.0.0-rc5"
sp-runtime = "2.0.0-rc5"
sunshine-node-utils = { git = "https://github.com/sunshine-protocol/sunshine-core" }
sunshine-pallet-utils = { git = "https://github.com/sunshine-protocol/sunshine-core" }
test-runtime = { path = "../runtime" }
# cli deps
sc-cli = "0.8.0-rc5"
sc-service = { version = "0.8.0-rc5", default-features = false }
structopt = "0.3.16"

[build-dependencies]
substrate-build-script-utils = "2.0.0-rc5"
