[package]
name = "test-cli"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>, Amar Singh <asinghchrony@protonmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "=1.5.0", features = ["attributes"] }
exitfailure = "0.5.1"
clap = "3.0.0-beta.1"
sunshine-client = { package = "sunshine-bounty-client", path = "../../client/client" }
dirs2 = "3.0.1"
env_logger = "0.7.1"
ipfs-embed = "0.1.1"
ipld-block-builder = "0.3.0"
keybase-keystore = {package = "keybase-keystore", git = "https://github.com/sunshine-protocol/substrate-identity"}
qr2term = "0.2.1"
rpassword = "4.0.5"
sp-keyring = "2.0.0-rc4"
pallet-indices = "2.0.0-rc4"
sp-core = "2.0.0-rc4"
substrate-subxt = "0.10.1"
# textwrap = { version = "0.11.0", features = ["term_size"] }
thiserror = "1.0.20"
utils-identity = { package = "sunshine-identity-utils", git = "https://github.com/sunshine-protocol/sunshine-identity/" }
